### ISSUE TITLE
ret의 역할

### ISSUE THREAD

**Issue by gvsteve24** [bcaitech1/team36-algorithm#13]
https://github.com/bcaitech1/team36-algorithm/blob/f6135be528e96b265d52f3cc68633a76943475bb/Algorithm/solution/BOJ17142.py#L34

조건을 보면 `lab[i][j]==2`또는 `lab[i][j] == 0`인 상황에서 `check_time[i][j] != -1`(도달하는 경우)에 
`ret = max(ret, check_time[i][j])` 가 실행되는 것을 알 수 있는데요.

그러면 ret초기값은 0이고 `lab[i][j] == 0`인 상황이면(바이러스 처음 시작위치) `check_time[i][j] == 0` 인데 max가 의미있게 작용하는지 모르겠습니다. 제가 어떤점을 잘못이해하고 있는걸까요?

**Comment by rjhwang08** [comment]
해당 부분에 대한 설명이 부족한 것 같아서 전반적으로 설명을 드리겠습니다.

말씀해주신 부분은, 해당 조합(M개의 바이러스 선택)에서 바이러스가 모든 공간에 퍼지는데 걸린 시간을 모두 check_time에 기록한 이후에 진행됩니다. -> 즉, ``while q:`` 반복문의 종료 이후입니다.

해당 조합에서의 시간 측정이 끝났다면, 이제 해당 조합이 최소 시간의 조합인지 확인이 필요합니다.
따라서 이중 for문을 통해 NxN 크기의 연구실의 모든 칸을 방문하여 check_time의 가장 큰 값을 찾아야 합니다.
여기서 ret은 최종적으로 해당 조합에서 가장 큰 값(연구실에 바이러스를 퍼뜨리는데 걸린 시간)을 반환하는 변수입니다.

말씀해주신 부분을 보면, ``lab[i][j]==2`` 또는 ``lab[i][j] == 0``인 상황 (-> 2: 바이러스, 0: 빈 칸)에서 
``check_time[i][j] == -1`` (-> 시간이 -1 == 방문하지 않음)이라면,
시간의 초기값이 -1이므로, 벽(``lab[i][j]==1``)이 아닌데 아직 -1이라면 바이러스가 모든 공간에 퍼지지 못했으므로 해당 조합은 실패했음을 알 수 있습니다.
따라서 ``return -1``을 실행합니다.

다음으로,
``if lab[i][j] == 0: ret = max(ret, check_time[i][j])`` -> 만약 현재 방문한 곳이 빈 칸이라면, 해당 빈 칸에 도달하는데 걸린 시간을 ret과 비교하여 갱신합니다.
하필 ``if lab[i][j] == 0:``인 이유는, 연구실의 모든 빈 공간에 퍼뜨리는 게 목적이기 때문입니다.
즉, ``if lab[i][j] == 2:`` 인 경우(비활성 바이러스)에 도착하는 시간은 제외하는 목적이죠.

이상으로 전반적으로 설명을 드렸습니다.
따라서, 질문에서 ``lab[i][j] == 0``인 상황은 바이러스 처음 시작 위치가 아니라 빈 칸의 위치이죠.
처음 시작 위치는 ``check_time[i][j] == 0``으로 볼 수 있겠죠.

부족한 부분이 있으면 다시 질문 부탁드리겠습니다!

**Comment by gvsteve24** [comment]
그렇군요!!!! 제가 `lab[i][j] == 0`이랑 `check_time[i][j] == 0`을 헷갈렸습니다. 
친절한 설명 감사드립니다~~~!
